// <auto-generated />
namespace CarReservation.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Ride : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ride));
        
        string IMigrationMetadata.Id
        {
            get { return "201611130820378_Ride"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
