// <auto-generated />
namespace CarReservation.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class VehiclePackage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VehiclePackage));
        
        string IMigrationMetadata.Id
        {
            get { return "201612222227086_VehiclePackage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
