namespace CarReservation.Core.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class packages : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.PackageTravelUnits", "Currency_Id", "dbo.Currencies");
            DropForeignKey("dbo.PackageTravelUnits", "TravelUnit_Id", "dbo.TravelUnits");
            DropForeignKey("dbo.PackageVehicleAssemblies", "Package_Id", "dbo.Packages");
            DropForeignKey("dbo.PackageVehicleAssemblies", "VehicleAssembly_Id", "dbo.VehicleAssemblies");
            DropForeignKey("dbo.PackageVehicleBodyTypes", "Package_Id", "dbo.Packages");
            DropForeignKey("dbo.PackageVehicleBodyTypes", "VehicleBodyType_Id", "dbo.VehicleBodyTypes");
            DropForeignKey("dbo.PackageVehicleFeatures", "Package_Id", "dbo.Packages");
            DropForeignKey("dbo.PackageVehicleFeatures", "VehicleFeature_Id", "dbo.VehicleFeatures");
            DropForeignKey("dbo.PackageVehicleModels", "Package_Id", "dbo.Packages");
            DropForeignKey("dbo.PackageVehicleModels", "VehicleModel_Id", "dbo.VehicleModels");
            DropForeignKey("dbo.PackageVehicleTransmissions", "Package_Id", "dbo.Packages");
            DropForeignKey("dbo.PackageVehicleTransmissions", "VehicleTransmission_Id", "dbo.VehicleTransmissions");
            DropIndex("dbo.PackageTravelUnits", new[] { "Currency_Id" });
            DropIndex("dbo.PackageTravelUnits", new[] { "Package_Id" });
            DropIndex("dbo.PackageTravelUnits", new[] { "TravelUnit_Id" });
            DropIndex("dbo.PackageVehicleAssemblies", new[] { "Package_Id" });
            DropIndex("dbo.PackageVehicleAssemblies", new[] { "VehicleAssembly_Id" });
            DropIndex("dbo.PackageVehicleBodyTypes", new[] { "Package_Id" });
            DropIndex("dbo.PackageVehicleBodyTypes", new[] { "VehicleBodyType_Id" });
            DropIndex("dbo.PackageVehicleFeatures", new[] { "Package_Id" });
            DropIndex("dbo.PackageVehicleFeatures", new[] { "VehicleFeature_Id" });
            DropIndex("dbo.PackageVehicleModels", new[] { "Package_Id" });
            DropIndex("dbo.PackageVehicleModels", new[] { "VehicleModel_Id" });
            DropIndex("dbo.PackageVehicleTransmissions", new[] { "Package_Id" });
            DropIndex("dbo.PackageVehicleTransmissions", new[] { "VehicleTransmission_Id" });
            RenameColumn(table: "dbo.PackageTravelUnits", name: "Currency_Id", newName: "CurrencyId");
            RenameColumn(table: "dbo.PackageTravelUnits", name: "Package_Id", newName: "PackageId");
            RenameColumn(table: "dbo.PackageTravelUnits", name: "TravelUnit_Id", newName: "TravelUnitId");
            RenameColumn(table: "dbo.PackageVehicleAssemblies", name: "Package_Id", newName: "PackageId");
            RenameColumn(table: "dbo.PackageVehicleAssemblies", name: "VehicleAssembly_Id", newName: "VehicleAssemblyId");
            RenameColumn(table: "dbo.PackageVehicleBodyTypes", name: "Package_Id", newName: "PackageId");
            RenameColumn(table: "dbo.PackageVehicleBodyTypes", name: "VehicleBodyType_Id", newName: "VehicleBodyTypeId");
            RenameColumn(table: "dbo.PackageVehicleFeatures", name: "Package_Id", newName: "PackageId");
            RenameColumn(table: "dbo.PackageVehicleFeatures", name: "VehicleFeature_Id", newName: "VehicleFeatureId");
            RenameColumn(table: "dbo.PackageVehicleModels", name: "Package_Id", newName: "PackageId");
            RenameColumn(table: "dbo.PackageVehicleModels", name: "VehicleModel_Id", newName: "VehicleModelId");
            RenameColumn(table: "dbo.PackageVehicleTransmissions", name: "Package_Id", newName: "PackageId");
            RenameColumn(table: "dbo.PackageVehicleTransmissions", name: "VehicleTransmission_Id", newName: "VehicleTransmissionId");
            AlterColumn("dbo.PackageTravelUnits", "CurrencyId", c => c.Int(nullable: false));
            AlterColumn("dbo.PackageTravelUnits", "PackageId", c => c.Int(nullable: false));
            AlterColumn("dbo.PackageTravelUnits", "TravelUnitId", c => c.Int(nullable: false));
            AlterColumn("dbo.PackageVehicleAssemblies", "PackageId", c => c.Int(nullable: false));
            AlterColumn("dbo.PackageVehicleAssemblies", "VehicleAssemblyId", c => c.Int(nullable: false));
            AlterColumn("dbo.PackageVehicleBodyTypes", "PackageId", c => c.Int(nullable: false));
            AlterColumn("dbo.PackageVehicleBodyTypes", "VehicleBodyTypeId", c => c.Int(nullable: false));
            AlterColumn("dbo.PackageVehicleFeatures", "PackageId", c => c.Int(nullable: false));
            AlterColumn("dbo.PackageVehicleFeatures", "VehicleFeatureId", c => c.Int(nullable: false));
            AlterColumn("dbo.PackageVehicleModels", "PackageId", c => c.Int(nullable: false));
            AlterColumn("dbo.PackageVehicleModels", "VehicleModelId", c => c.Int(nullable: false));
            AlterColumn("dbo.PackageVehicleTransmissions", "PackageId", c => c.Int(nullable: false));
            AlterColumn("dbo.PackageVehicleTransmissions", "VehicleTransmissionId", c => c.Int(nullable: false));
            CreateIndex("dbo.PackageTravelUnits", "CurrencyId");
            CreateIndex("dbo.PackageTravelUnits", "PackageId");
            CreateIndex("dbo.PackageTravelUnits", "TravelUnitId");
            CreateIndex("dbo.PackageVehicleAssemblies", "PackageId");
            CreateIndex("dbo.PackageVehicleAssemblies", "VehicleAssemblyId");
            CreateIndex("dbo.PackageVehicleBodyTypes", "PackageId");
            CreateIndex("dbo.PackageVehicleBodyTypes", "VehicleBodyTypeId");
            CreateIndex("dbo.PackageVehicleFeatures", "PackageId");
            CreateIndex("dbo.PackageVehicleFeatures", "VehicleFeatureId");
            CreateIndex("dbo.PackageVehicleModels", "PackageId");
            CreateIndex("dbo.PackageVehicleModels", "VehicleModelId");
            CreateIndex("dbo.PackageVehicleTransmissions", "PackageId");
            CreateIndex("dbo.PackageVehicleTransmissions", "VehicleTransmissionId");
            AddForeignKey("dbo.PackageTravelUnits", "CurrencyId", "dbo.Currencies", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PackageTravelUnits", "TravelUnitId", "dbo.TravelUnits", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PackageVehicleAssemblies", "PackageId", "dbo.Packages", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PackageVehicleAssemblies", "VehicleAssemblyId", "dbo.VehicleAssemblies", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PackageVehicleBodyTypes", "PackageId", "dbo.Packages", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PackageVehicleBodyTypes", "VehicleBodyTypeId", "dbo.VehicleBodyTypes", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PackageVehicleFeatures", "PackageId", "dbo.Packages", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PackageVehicleFeatures", "VehicleFeatureId", "dbo.VehicleFeatures", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PackageVehicleModels", "PackageId", "dbo.Packages", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PackageVehicleModels", "VehicleModelId", "dbo.VehicleModels", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PackageVehicleTransmissions", "PackageId", "dbo.Packages", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PackageVehicleTransmissions", "VehicleTransmissionId", "dbo.VehicleTransmissions", "Id", cascadeDelete: true);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.PackageVehicleTransmissions", "VehicleTransmissionId", "dbo.VehicleTransmissions");
            DropForeignKey("dbo.PackageVehicleTransmissions", "PackageId", "dbo.Packages");
            DropForeignKey("dbo.PackageVehicleModels", "VehicleModelId", "dbo.VehicleModels");
            DropForeignKey("dbo.PackageVehicleModels", "PackageId", "dbo.Packages");
            DropForeignKey("dbo.PackageVehicleFeatures", "VehicleFeatureId", "dbo.VehicleFeatures");
            DropForeignKey("dbo.PackageVehicleFeatures", "PackageId", "dbo.Packages");
            DropForeignKey("dbo.PackageVehicleBodyTypes", "VehicleBodyTypeId", "dbo.VehicleBodyTypes");
            DropForeignKey("dbo.PackageVehicleBodyTypes", "PackageId", "dbo.Packages");
            DropForeignKey("dbo.PackageVehicleAssemblies", "VehicleAssemblyId", "dbo.VehicleAssemblies");
            DropForeignKey("dbo.PackageVehicleAssemblies", "PackageId", "dbo.Packages");
            DropForeignKey("dbo.PackageTravelUnits", "TravelUnitId", "dbo.TravelUnits");
            DropForeignKey("dbo.PackageTravelUnits", "CurrencyId", "dbo.Currencies");
            DropIndex("dbo.PackageVehicleTransmissions", new[] { "VehicleTransmissionId" });
            DropIndex("dbo.PackageVehicleTransmissions", new[] { "PackageId" });
            DropIndex("dbo.PackageVehicleModels", new[] { "VehicleModelId" });
            DropIndex("dbo.PackageVehicleModels", new[] { "PackageId" });
            DropIndex("dbo.PackageVehicleFeatures", new[] { "VehicleFeatureId" });
            DropIndex("dbo.PackageVehicleFeatures", new[] { "PackageId" });
            DropIndex("dbo.PackageVehicleBodyTypes", new[] { "VehicleBodyTypeId" });
            DropIndex("dbo.PackageVehicleBodyTypes", new[] { "PackageId" });
            DropIndex("dbo.PackageVehicleAssemblies", new[] { "VehicleAssemblyId" });
            DropIndex("dbo.PackageVehicleAssemblies", new[] { "PackageId" });
            DropIndex("dbo.PackageTravelUnits", new[] { "TravelUnitId" });
            DropIndex("dbo.PackageTravelUnits", new[] { "PackageId" });
            DropIndex("dbo.PackageTravelUnits", new[] { "CurrencyId" });
            AlterColumn("dbo.PackageVehicleTransmissions", "VehicleTransmissionId", c => c.Int());
            AlterColumn("dbo.PackageVehicleTransmissions", "PackageId", c => c.Int());
            AlterColumn("dbo.PackageVehicleModels", "VehicleModelId", c => c.Int());
            AlterColumn("dbo.PackageVehicleModels", "PackageId", c => c.Int());
            AlterColumn("dbo.PackageVehicleFeatures", "VehicleFeatureId", c => c.Int());
            AlterColumn("dbo.PackageVehicleFeatures", "PackageId", c => c.Int());
            AlterColumn("dbo.PackageVehicleBodyTypes", "VehicleBodyTypeId", c => c.Int());
            AlterColumn("dbo.PackageVehicleBodyTypes", "PackageId", c => c.Int());
            AlterColumn("dbo.PackageVehicleAssemblies", "VehicleAssemblyId", c => c.Int());
            AlterColumn("dbo.PackageVehicleAssemblies", "PackageId", c => c.Int());
            AlterColumn("dbo.PackageTravelUnits", "TravelUnitId", c => c.Int());
            AlterColumn("dbo.PackageTravelUnits", "PackageId", c => c.Int());
            AlterColumn("dbo.PackageTravelUnits", "CurrencyId", c => c.Int());
            RenameColumn(table: "dbo.PackageVehicleTransmissions", name: "VehicleTransmissionId", newName: "VehicleTransmission_Id");
            RenameColumn(table: "dbo.PackageVehicleTransmissions", name: "PackageId", newName: "Package_Id");
            RenameColumn(table: "dbo.PackageVehicleModels", name: "VehicleModelId", newName: "VehicleModel_Id");
            RenameColumn(table: "dbo.PackageVehicleModels", name: "PackageId", newName: "Package_Id");
            RenameColumn(table: "dbo.PackageVehicleFeatures", name: "VehicleFeatureId", newName: "VehicleFeature_Id");
            RenameColumn(table: "dbo.PackageVehicleFeatures", name: "PackageId", newName: "Package_Id");
            RenameColumn(table: "dbo.PackageVehicleBodyTypes", name: "VehicleBodyTypeId", newName: "VehicleBodyType_Id");
            RenameColumn(table: "dbo.PackageVehicleBodyTypes", name: "PackageId", newName: "Package_Id");
            RenameColumn(table: "dbo.PackageVehicleAssemblies", name: "VehicleAssemblyId", newName: "VehicleAssembly_Id");
            RenameColumn(table: "dbo.PackageVehicleAssemblies", name: "PackageId", newName: "Package_Id");
            RenameColumn(table: "dbo.PackageTravelUnits", name: "TravelUnitId", newName: "TravelUnit_Id");
            RenameColumn(table: "dbo.PackageTravelUnits", name: "PackageId", newName: "Package_Id");
            RenameColumn(table: "dbo.PackageTravelUnits", name: "CurrencyId", newName: "Currency_Id");
            CreateIndex("dbo.PackageVehicleTransmissions", "VehicleTransmission_Id");
            CreateIndex("dbo.PackageVehicleTransmissions", "Package_Id");
            CreateIndex("dbo.PackageVehicleModels", "VehicleModel_Id");
            CreateIndex("dbo.PackageVehicleModels", "Package_Id");
            CreateIndex("dbo.PackageVehicleFeatures", "VehicleFeature_Id");
            CreateIndex("dbo.PackageVehicleFeatures", "Package_Id");
            CreateIndex("dbo.PackageVehicleBodyTypes", "VehicleBodyType_Id");
            CreateIndex("dbo.PackageVehicleBodyTypes", "Package_Id");
            CreateIndex("dbo.PackageVehicleAssemblies", "VehicleAssembly_Id");
            CreateIndex("dbo.PackageVehicleAssemblies", "Package_Id");
            CreateIndex("dbo.PackageTravelUnits", "TravelUnit_Id");
            CreateIndex("dbo.PackageTravelUnits", "Package_Id");
            CreateIndex("dbo.PackageTravelUnits", "Currency_Id");
            AddForeignKey("dbo.PackageVehicleTransmissions", "VehicleTransmission_Id", "dbo.VehicleTransmissions", "Id");
            AddForeignKey("dbo.PackageVehicleTransmissions", "Package_Id", "dbo.Packages", "Id");
            AddForeignKey("dbo.PackageVehicleModels", "VehicleModel_Id", "dbo.VehicleModels", "Id");
            AddForeignKey("dbo.PackageVehicleModels", "Package_Id", "dbo.Packages", "Id");
            AddForeignKey("dbo.PackageVehicleFeatures", "VehicleFeature_Id", "dbo.VehicleFeatures", "Id");
            AddForeignKey("dbo.PackageVehicleFeatures", "Package_Id", "dbo.Packages", "Id");
            AddForeignKey("dbo.PackageVehicleBodyTypes", "VehicleBodyType_Id", "dbo.VehicleBodyTypes", "Id");
            AddForeignKey("dbo.PackageVehicleBodyTypes", "Package_Id", "dbo.Packages", "Id");
            AddForeignKey("dbo.PackageVehicleAssemblies", "VehicleAssembly_Id", "dbo.VehicleAssemblies", "Id");
            AddForeignKey("dbo.PackageVehicleAssemblies", "Package_Id", "dbo.Packages", "Id");
            AddForeignKey("dbo.PackageTravelUnits", "TravelUnit_Id", "dbo.TravelUnits", "Id");
            AddForeignKey("dbo.PackageTravelUnits", "Currency_Id", "dbo.Currencies", "Id");
        }
    }
}
